name: Deploy

on:
  push:
    branches: [main]
jobs:
  flatpak:
    strategy:
      matrix:
        runs-on: [ARM64, ubuntu-latest]
    name: "Flatpak"
    runs-on: ${{ matrix.runs-on }}
    container:
      image: freedesktopsdk/flatpak:20.08
      options: --privileged
    steps:
    - uses: actions/checkout@v2
    - uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v4
      name: "Build"
      with:
        bundle: modi.flatpak
        manifest-path: co.tauos.Modi.json
        cache-key: flatpak-builder-${{ github.sha }}
        repository-name: catalogue
        repository-url: https://repo.tauos.co/catalogue.flatpakrepo
    - uses: bilelmoussaoui/flatpak-github-actions/flat-manager@v3
      name: "Deploy"
      with:
        repository: stable
        flat-manager-url: https://catalogue.tauos.co
        token: ${{ secrets.FLATPAK_REPO_TOKEN }}
